### ISSUE TITLE
midterm topics

### ISSUE THREAD

**Issue by ceska** [2160559/WEB-TECH-LEC#3]
*last updated: 9 april 18*

let's organize midterms so we won't have to rush again, lol. so i was thinking that every week, we'll comment all the topics sir had discussed here, and one or two people will be assigned for documentation. no deadline, but it's probably better to have it finished within two weeks.

reminder: remember to check done assigned topics below (beside the topic) and push it to the repo in the *documentation - midterms* folder~

### midterms
*2 march 18* - **nic**
- [x] css history
- [x] html stylesheets
- [x] css statements
- [x] css rule set

*6 march 18* - **karen**
- [x] definition
- [x] css syntax
- [x]  invalid selector
- [x] selectors in actual use /demonstration /illustration
  - [x] Simple Selector categories - **gaspar**
  - [x] Combinators categories - **rafii**
  - [x] Pseudo elements categories - **pagz**

*13 march 18* - **karen**
- [x] css rule precedence

*16 march 18* - **nic**
- [x] css declaration (css properties and css values, categories)
- [x] css preprocessors, framework

*23 march 18*
- [x] js definition - **pags**
- [x] how to associate JS (script element) - **karen**
- [x] js execution environment - **nic**

*3 april 2018*
- [x] js language fundamentals - **ces**

*6 april 2018*
- [x] js event handling (needs some sample codes though) - **pags**

*7 april 2018*
- [ ] dynamic content loading
- [ ] ajax
- [x] js asynchronous - karen
- [x] js promises - nic

**Comment by jungas** [comment]
we also need to add quizzes for prelims and midterms

**Comment by 2161478** [comment]
can i make the documentation of last March 2 2018's lecture? i think its about css history.

**Comment by 2160559** [comment]
hmmm. for the assignment of documentation. i think it would be better if we ask for volunteers first then  last name alphabetical order for those who didn't document for midterms. we can also do this for the finals. if you want. 

For the quizzes. we still have to decide if we're going to do the quiz per topic or by chapter
