### ISSUE TITLE
prelims topics

### ISSUE THREAD

**Issue by 2160559** [2160559/WEB-TECH-LEC#5]
**WWW**
-definition
-bullets for elaboration
-example / diagram 
-explanation

**HTTP**
1. introduction
    -definition
    -characteristics
    -communication
    -intermediaries
2. version/evolution
    -0.9
    -1.0
    -1.1
    -2.0
3. message 
    -definition /types
    -parts of a message for response and request
    -diagram or example with labelled parts
        omethods 
       oheaders
       ostatus codes
4. features
    -include authentication
    -create extension

**URL**
-definition
-parts with diagram
examples?
-url encoded query

**HTML**
1.introduction
    -definition or uses
    -basic html structure
2.versions
3. pre processors
4. html forms

**Comment by ceska** [comment]
incomplete/still needs some documentation for certain topics/subtopics
[re-edit prelims.docx](https://github.com/2160559/WEB-TECH-LEC/files/1789580/re-edit.prelims.docx)
